### ISSUE TITLE
Error: Calling <<-EOS.undent is disabled

### ISSUE THREAD

**Issue by shiumachi** [chezou/homebrew-cloudera#6]
I got the following error when I try to update Director to 2.7.1.

```
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/chezou/homebrew-cloudera/cloudera-director-server.rb:19:in `caveats'
Please report this to the chezou/cloudera tap!
Or, even better, submit a PR to fix it!
```

MacOS version: 10.12
Homebrew version: 1.6.1
Ruby version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

**Comment by shiumachi** [comment]
I found the same issue here: https://github.com/Homebrew/brew/issues/3738

**Comment by Fundebug** [comment]
FYI, I solved the problem by just update brew:

```bash
brew update
```
